name: Publish to Rubygems

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Publish to Rubygems
      uses: cadwallion/publish-rubygems-action@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
